### PR TITLE
Data frame implementation of extractors. Also added cmd arguments to resolve #235

### LINKED ISSUE #235: CommandLineAppRunner.scala produces output per WARC instead of combined result.
**Describe the bug**
Comes from #225.  Instead of single Gexf file from the RDD[ArchiveRecord] we get one per warc file.  This will not work for our applications in auk etc.

**To Reproduce**
Steps to reproduce the behavior (e.g.):
1. Use the CommandLineAppRunner to produce an output from a directory of warcs.
2. Result will have multiple gexf / txt etc.

**Expected behavior**
A single gexf file produced from the combined directory / rdd.

**Desktop/Laptop (please complete the following information):**
 - OS: [e.g. MacOS 10.13.4]
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**
The output for gexf also outputs a directory based on the warcfile and then GEXF.xml instead of just filename.graphml or filename.gexf inside an output directory.  This should be changed.

**Suggestion** remove `.foreach()` call from the second `args.input()` call as we usually want to conduct filtering / analysis on the entire rdd.    The output should simply be `filename.graphml` or `filename.gexf` etc.

### PR DESCRIPTION
**Pull request by TitusAn**
**Data frame implementation of extractors.  Also added cmd arguments to resolve #235**

* * *

**GitHub issue(s)**:

* #235 
* #223 

# What does this Pull Request do?

Added data frame implementation and tests for DomainFrequencyExtractor, DomainGraphExtractor and PlainTextExtractor. 

Also added new command line flags:

- If --df is present, the program will use data frame to carry out analysis
 

- If --split is present, the program will put results for each input file in its own folder. Otherwise they will be merged.

- If --partition N is present, the program will partition RDD or Data Frame according to N before writing results. Otherwise, partition is left as is.

# How should this be tested?

`mvn install` to run tests. Run jobs with `--df` option to use data frame implementation.

# Additional Notes:

Data frame tests for DomainGraphExtractor is missing because the result is different from RDD implementation. (It has more vertices and edges.) I am investigating this and will provide update.

# Interested parties

@lintool @greebie @ianmilligan1

### CODE REVIEW

File: src/main/scala/io/archivesunleashed/app/CommandLineApp.scala [hunk 1]
```diff
@@ -0,0 +1,237 @@
...
+ *
+ * If --df is present, the program will use data frame to carry out analysis
+ *
+ * If --split is present, the program will put results for each input file in its own folder. Otherwise they will be merged.
+ *
+ * If --partition N is present, the program will partition RDD or Data Frame according to N before writing results. Otherwise,
+ * partition is left as is.
+ */
+
+class CmdAppConf(args: Seq[String]) extends ScallopConf(args) {
```
Comment (ruebot) [inline src/main/scala/io/archivesunleashed/app/CommandLineApp.scala]: Missing lots of doc comments https://docs.scala-lang.org/style/scaladoc.html

File: src/main/scala/io/archivesunleashed/app/DomainGraphExtractor.scala [hunk 2]
```diff
@@ -19,16 +19,33 @@ package io.archivesunleashed.app
...
+      .flatMap(r => r._2.map(f =>
+        (r._1,
+          ExtractDomain(f._1).replaceAll("^\\\\s*www\\\\.", ""),
+          ExtractDomain(f._2).replaceAll("^\\\\s*www\\\\.", ""))
+        ))
       .filter(r => r._2 != "" && r._3 != "")
       .countItems()
       .filter(r => r._2 > 5)
   }
+  def apply(d: DataFrame): Dataset[Row] = {
```
Comment (ruebot) [inline src/main/scala/io/archivesunleashed/app/DomainGraphExtractor.scala]: Line break, and doc comment https://docs.scala-lang.org/style/scaladoc.html

File: src/main/scala/io/archivesunleashed/app/DomainGraphExtractor.scala [hunk 3]
```diff
@@ -19,16 +19,33 @@ package io.archivesunleashed.app
...
+    val spark = SparkSession.builder().master("local").getOrCreate()
+    import spark.implicits._
+
+    d.select($"CrawlDate",
+             df.RemovePrefixWWW(df.ExtractDomain($"Src")).as("SrcDomain"),
```
Comment (ruebot) [inline src/main/scala/io/archivesunleashed/app/DomainGraphExtractor.scala]: spaces, not tabs

File: src/main/scala/io/archivesunleashed/app/PlainTextExtractor.scala [hunk 4]
```diff
@@ -17,14 +17,22 @@
...
 import org.apache.spark.rdd.RDD
+import org.apache.spark.sql.{DataFrame, Dataset, Row, SparkSession}
 
 object PlainTextExtractor {
   def apply(records: RDD[ArchiveRecord]) = {
     records
       .keepValidPages()
       .map(r => (r.getCrawlDate, r.getDomain, r.getUrl, RemoveHTML(r.getContentString)))
   }
+  def apply(d: DataFrame): Dataset[Row] = {
```
Comment (ruebot) [inline src/main/scala/io/archivesunleashed/app/PlainTextExtractor.scala]: Line break, and doc comment needed https://docs.scala-lang.org/style/scaladoc.html

File: src/main/scala/io/archivesunleashed/app/WriteGEXF.scala [hunk 5]
```diff
@@ -39,6 +39,11 @@ object WriteGEXF {
     else makeFile (rdd, gexfPath)
   }
 
+  def apply(ds: Dataset[Row], gexfPath: String): Boolean = {
```
Comment (ruebot) [inline src/main/scala/io/archivesunleashed/app/WriteGEXF.scala]: doc comment https://docs.scala-lang.org/style/scaladoc.html

File: src/main/scala/io/archivesunleashed/app/WriteGEXF.scala [hunk 6]
```diff
@@ -76,6 +81,47 @@ object WriteGEXF {
     edges.foreach(r => outFile.write(r))
     outFile.write("</edges>\n</graph>\n</gexf>")
     outFile.close()
-    return true
+    true
+  }
+
+  def makeFile(ds: Dataset[Row], gexfPath: String): Boolean = {
```
Comment (ruebot) [inline src/main/scala/io/archivesunleashed/app/WriteGEXF.scala]: doc comment https://docs.scala-lang.org/style/scaladoc.html

**Comment by lintool** [comment]
@TitusAn I would suggest renaming the DF `ExtractDomain` to `ExtractBaseDomain` since it also removes the `www` prefix. Giving it a different name will also reduce confusion in the `matchbox` version since it does something different.

**Comment by lintool** [comment]
@TitusAn nudge on this issue? I want to get this merged in because there are a number of issues I want to address that this is blocking...

**Comment by TitusAn** [comment]
Sorry about that! I will finish this by end of today.

**Comment by ianmilligan1** [comment]
Looking good! Quick request just as we will eventually be documenting all this. In the PR you write:

>Added data frame implementation and tests for DomainFrequencyExtractor, DomainGraphExtractor and PlainTextExtractor. 
>
>Also added new command line flags:
>
>- If --df is present, the program will use data frame to carry out analysis
 >
>- If --split is present, the program will put results for each input file in its own folder. Otherwise they will be merged.
>
>- If --partition N is present, the program will partition RDD or Data Frame according to N before writing results. Otherwise, partition is left as is.

Would you be able to give a code example for each one (say running on a directory of sample WARCs)? I'm worried down the line when we document we'll lose the context of where things are. 😄

File: src/main/scala/io/archivesunleashed/app/CommandLineApp.scala [hunk 7]
```diff
@@ -0,0 +1,343 @@
...
+  val output = opt[String](descr = "output directory path", required = true)
+  val outputFormat = opt[String](descr =
+    "output format for DomainGraphExtractor, one of TEXT or GEXF")
+  val split = opt[Boolean]()
+  val df = opt[Boolean]()
+  val partition = opt[Int]()
+  verify()
+}
+
+/** Main application that parse
```
Comment (ruebot) [inline src/main/scala/io/archivesunleashed/app/CommandLineApp.scala]: Incomplete sentence?

File: src/main/scala/io/archivesunleashed/app/CommandLineApp.scala [hunk 8]
```diff
@@ -0,0 +1,343 @@
...
+
+  def save(d: Dataset[Row]): Unit = {
+    if (!configuration.partition.isEmpty) {
+      d.coalesce(configuration.partition()).write.csv(saveTarget)
+    } else {
+      d.write.csv(saveTarget)
+    }
+  }
+
+  /** Generic routine for saving RDD obtained from Map Reduce operation of extractors
```
Comment (ruebot) [inline src/main/scala/io/archivesunleashed/app/CommandLineApp.scala]: Full stop (period) at the end of line.

File: src/main/scala/io/archivesunleashed/app/CommandLineApp.scala [hunk 9]
```diff
@@ -0,0 +1,343 @@
...
+          save(DomainGraphExtractor(rdd))
+        }
+      }),
+    "PlainTextExtractor" ->
+      ((rdd: RDD[ArchiveRecord]) => {
+        save(PlainTextExtractor(rdd))
+      })
+  )
+
+  /** Maps extractor type string to Data Frame Extractors
```
Comment (ruebot) [inline src/main/scala/io/archivesunleashed/app/CommandLineApp.scala]: Full stop (period) at the end of line.

File: src/main/scala/io/archivesunleashed/app/CommandLineApp.scala [hunk 10]
```diff
@@ -0,0 +1,343 @@
...
+        saveTarget =  Paths.get(configuration.output(), Paths.get(f).getFileName.toString).toString
+        extractFunction(List[String](f))
+      }
+    } else {
+      saveTarget = Paths.get(configuration.output()).toString
+      extractFunction(configuration.input())
+    }
+  }
+
+  /** Prepare for invoking RDD implementation of extractors
```
Comment (ruebot) [inline src/main/scala/io/archivesunleashed/app/CommandLineApp.scala]: Full stop (period) at the end of line.

File: src/main/scala/io/archivesunleashed/app/CommandLineApp.scala [hunk 11]
```diff
@@ -0,0 +1,343 @@
...
+      nameList.tail foreach { f =>
+        rdd = rdd.union(RecordLoader.loadArchives(f, sparkCtx.get))
+      }
+      saveTarget = Paths.get(configuration.output()).toString
+      extractFunction(rdd)
+    }
+  }
+
+  /** Choose either Data Frame implementation or RDD implementation of extractors
+    * depending on the option specified in command line arguments
```
Comment (ruebot) [inline src/main/scala/io/archivesunleashed/app/CommandLineApp.scala]: Full stop (period) at the end of line.

File: src/main/scala/io/archivesunleashed/app/CommandLineApp.scala [hunk 12]
```diff
@@ -0,0 +1,343 @@
...
+    *
+    * @return Any
+    */
+
```
Comment (ruebot) [inline src/main/scala/io/archivesunleashed/app/CommandLineApp.scala]: Remove blank line.

File: src/main/scala/io/archivesunleashed/app/CommandLineApp.scala [hunk 13]
```diff
@@ -0,0 +1,343 @@
...
+  def process() = {
+    if (!configuration.df.isEmpty && configuration.df()) {
+      dfHandler()
+    } else {
+      rddHandler()
+    }
+  }
+
+  def setSparkContext(sc: SparkContext): Unit = {
```
Comment (ruebot) [inline src/main/scala/io/archivesunleashed/app/CommandLineApp.scala]: Missing doc comment.

File: src/main/scala/io/archivesunleashed/app/CommandLineApp.scala [hunk 14]
```diff
@@ -0,0 +1,343 @@
...
+    sparkCtx = Some(sc)
+  }
+}
+
+object CommandLineAppRunner {
+
+  /** Entry point for command line application
```
Comment (ruebot) [inline src/main/scala/io/archivesunleashed/app/CommandLineApp.scala]: Full stop (period) at the end of line.

File: src/main/scala/io/archivesunleashed/app/CommandLineApp.scala [hunk 15]
```diff
@@ -0,0 +1,343 @@
...
+    }
+
+    val conf = new SparkConf().setAppName("AUTCommandLineApp")
+    conf.set("spark.driver.allowMultipleContexts", "true")
+    app.setSparkContext(new SparkContext(conf))
+    app.process()
+  }
+
+  /** Entry point for testing.
+    * Takes an existed spark session to prevent new ones from being created
```
Comment (ruebot) [inline src/main/scala/io/archivesunleashed/app/CommandLineApp.scala]: Full stop (period) at the end of line.

File: src/main/scala/io/archivesunleashed/app/CommandLineApp.scala [hunk 16]
```diff
@@ -0,0 +1,343 @@
...
+    *
+    * @param argv command line arguments (array of strings) .
```
Comment (ruebot) [inline src/main/scala/io/archivesunleashed/app/CommandLineApp.scala]: Remove extra space and full stop at end of line.

File: src/main/scala/io/archivesunleashed/app/DomainFrequencyExtractor.scala [hunk 17]
```diff
@@ -18,14 +18,35 @@
...
+    */
   def apply(records: RDD[ArchiveRecord]) = {
       records
         .keepValidPages()
-        .map(r => ExtractDomain(r.getUrl))
+        .map(r => matchbox.ExtractDomain(r.getUrl))
         .countItems()
   }
+
+  /** Extract domain frequency from web archive using Data Frame and Spark SQL
```
Comment (ruebot) [inline src/main/scala/io/archivesunleashed/app/DomainFrequencyExtractor.scala]: Full stop (period) at the end of line.

File: src/main/scala/io/archivesunleashed/app/DomainGraphExtractor.scala [hunk 18]
```diff
@@ -19,16 +19,45 @@ package io.archivesunleashed.app
...
+        (r._1,
+          ExtractDomain(f._1).replaceAll("^\\\\s*www\\\\.", ""),
+          ExtractDomain(f._2).replaceAll("^\\\\s*www\\\\.", ""))
+        ))
       .filter(r => r._2 != "" && r._3 != "")
       .countItems()
       .filter(r => r._2 > 5)
   }
+
+  /** Extract domain graph from web archive using Data Frame and Spark SQL
```
Comment (ruebot) [inline src/main/scala/io/archivesunleashed/app/DomainGraphExtractor.scala]: Full stop (period) at the end of line.

File: src/main/scala/io/archivesunleashed/app/PlainTextExtractor.scala [hunk 19]
```diff
@@ -17,14 +17,34 @@
...
+    * @return RDD[(String, String, String, String)], which holds
+    *         (CrawlDate, Domain, Url, Text)
+    */
   def apply(records: RDD[ArchiveRecord]) = {
     records
       .keepValidPages()
       .map(r => (r.getCrawlDate, r.getDomain, r.getUrl, RemoveHTML(r.getContentString)))
   }
+
+  /** Extract plain text from web archive using Data Frame and Spark SQL
```
Comment (ruebot) [inline src/main/scala/io/archivesunleashed/app/PlainTextExtractor.scala]: Full stop (period) at the end of line.

**Comment by TitusAn** [comment]
@ianmilligan1 

Here are some example usage for new flags:

```
--df 

./aut_runtree/spark-2.3.0-bin-hadoop2.7/bin/spark-submit --class io.archivesunleashed.app.CommandLineAppRunner ./aut_self/aut/target/aut-0.16.1-SNAPSHOT-fatjar.jar --extractor DomainGraphExtractor --input ./aut_self/aut/src/test/resources/warc/example.warc.gz ./aut_self/aut/src/test/resources/arc/example.arc.gz  --output output1 --df 
```

Data frame implementation of DomainGraphExtractor is used.


```
--partition:

./aut_runtree/spark-2.3.0-bin-hadoop2.7/bin/spark-submit --class io.archivesunleashed.app.CommandLineAppRunner ./aut_self/aut/target/aut-0.16.1-SNAPSHOT-fatjar.jar --extractor DomainFrequencyExtractor --input ./aut_self/aut/src/test/resources/warc/example.warc.gz ./aut_self/aut/src/test/resources/arc/example.arc.gz  --output output2 --df  --partition 1
```

Output will be a single file rather than PART-0000, PART-0001, etc.

```
--split 

./aut_runtree/spark-2.3.0-bin-hadoop2.7/bin/spark-submit --class io.archivesunleashed.app.CommandLineAppRunner ./aut_self/aut/target/aut-0.16.1-SNAPSHOT-fatjar.jar --extractor DomainFrequencyExtractor --input ./aut_self/aut/src/test/resources/warc/example.warc.gz ./aut_self/aut/src/test/resources/arc/example.arc.gz  --output output3 --df  --split
```
Results for example.arc.gz and example.warc.gz will be in their own directory, rather than merged together.
